

import { Board, Column, Task, User } from '../types';

const API_BASE_URL = 'http://localhost:3001/api';

export const api = {
  getBoards: async (): Promise<Board[]> => {
    const response = await fetch(`${API_BASE_URL}/boards`);
    if (!response.ok) throw new Error('Failed to fetch boards');
    return response.json();
  },

  createBoard: async (title: string, background: string): Promise<Board> => {
    const response = await fetch(`${API_BASE_URL}/boards`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ 
        id: `board-${Date.now()}`, // Ideally ID is generated by DB, but sending for consistency with current types
        title, 
        background 
      }),
    });
    if (!response.ok) throw new Error('Failed to create board');
    return response.json();
  },

  updateBoard: async (updatedBoard: Board): Promise<void> => {
    const response = await fetch(`${API_BASE_URL}/boards/${updatedBoard.id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(updatedBoard),
    });
    if (!response.ok) throw new Error('Failed to update board');
  },

  deleteBoard: async (boardId: string): Promise<void> => {
    const response = await fetch(`${API_BASE_URL}/boards/${boardId}`, {
      method: 'DELETE',
    });
    if (!response.ok) throw new Error('Failed to delete board');
  },

  getColumns: async (boardId: string): Promise<Column[]> => {
    const response = await fetch(`${API_BASE_URL}/boards/${boardId}/columns`);
    if (!response.ok) throw new Error('Failed to fetch columns');
    return response.json();
  },

  updateColumn: async (columnId: string, title: string): Promise<void> => {
    const response = await fetch(`${API_BASE_URL}/columns/${columnId}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title }),
    });
    if (!response.ok) throw new Error('Failed to update column');
  },

  deleteColumn: async (columnId: string): Promise<void> => {
    const response = await fetch(`${API_BASE_URL}/columns/${columnId}`, {
      method: 'DELETE',
    });
    if (!response.ok) throw new Error('Failed to delete column');
  },

  addColumn: async (title: string, boardId: string): Promise<Column> => {
    const response = await fetch(`${API_BASE_URL}/columns`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title, boardId }),
    });
    if (!response.ok) throw new Error('Failed to add column');
    return response.json();
  },

  getTasks: async (boardId: string): Promise<Task[]> => {
    const response = await fetch(`${API_BASE_URL}/boards/${boardId}/tasks`);
    if (!response.ok) throw new Error('Failed to fetch tasks');
    return response.json();
  },

  // New Search Method
  searchTasks: async (query: string): Promise<Task[]> => {
    const response = await fetch(`${API_BASE_URL}/search?q=${encodeURIComponent(query)}`);
    if (!response.ok) throw new Error('Failed to search tasks');
    return response.json();
  },

  updateTask: async (updatedTask: Task): Promise<void> => {
    const response = await fetch(`${API_BASE_URL}/tasks/${updatedTask.id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(updatedTask),
    });
    if (!response.ok) throw new Error('Failed to update task');
  },

  reorderTask: async (taskId: string, targetColumnId: string, newIndex: number): Promise<void> => {
    const response = await fetch(`${API_BASE_URL}/tasks/${taskId}/reorder`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ targetColumnId, newIndex }),
    });
    if (!response.ok) throw new Error('Failed to reorder task');
  },

  addTask: async (task: Task): Promise<void> => {
    const response = await fetch(`${API_BASE_URL}/tasks`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(task),
    });
    if (!response.ok) throw new Error('Failed to add task');
  },

  deleteTask: async (taskId: string): Promise<void> => {
    const response = await fetch(`${API_BASE_URL}/tasks/${taskId}`, {
      method: 'DELETE',
    });
    if (!response.ok) throw new Error('Failed to delete task');
  },

  // Auth Methods
  register: async (name: string, email: string, password: string): Promise<User> => {
    const response = await fetch(`${API_BASE_URL}/auth/register`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name, email, password }),
    });
    
    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.message || 'Registration failed');
    }
    return response.json();
  },

  login: async (email: string, password: string): Promise<User> => {
    const response = await fetch(`${API_BASE_URL}/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password }),
    });
    
    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.message || 'Login failed');
    }
    return response.json();
  },

  getUsers: async (): Promise<User[]> => {
    const response = await fetch(`${API_BASE_URL}/users`);
    if (!response.ok) throw new Error('Failed to fetch users');
    return response.json();
  },

  updateUser: async (updatedUser: User): Promise<void> => {
    const response = await fetch(`${API_BASE_URL}/users/${updatedUser.id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(updatedUser),
    });
    if (!response.ok) throw new Error('Failed to update user');
  }
};